version: '3.7'

services:
    db:
        image: postgres:11.12
        restart: always
        environment:
            POSTGRES_USER: 'help_to_grow'
            POSTGRES_PASSWORD: 'help_to_grow_db_password'
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - 5439:5432
        volumes:
            - ./volumes/postgres-data:/var/lib/postgresql/data