name: CI Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'main'
      - 'release/**'
      - 'hotfix/**'
  pull_request:
    branches: 
     - 'master'
     - 'main'
     - 'release/**'
     - 'hotfix/**'
env:
  REGISTRY_LOGIN_SERVER: htgdevregistry.azurecr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
